# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui2.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FACELOOK(object):
    def setupUi(self, FACELOOK):
        FACELOOK.setObjectName("FACELOOK")
        FACELOOK.resize(1149, 710)
        self.backGroundFrame = QtWidgets.QFrame(FACELOOK)
        self.backGroundFrame.setGeometry(QtCore.QRect(0, 0, 1151, 711))
        self.backGroundFrame.setStyleSheet("#backGroundFrame {\n"
"    border-image: url(:/0.png);\n"
"    border-radius: 0px;\n"
"}")
        self.backGroundFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.backGroundFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.backGroundFrame.setObjectName("backGroundFrame")
        self.cameraButton = QtWidgets.QPushButton(self.backGroundFrame)
        self.cameraButton.setGeometry(QtCore.QRect(200, 630, 141, 41))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(15)
        self.cameraButton.setFont(font)
        self.cameraButton.setStyleSheet("QPushButton{\n"
"    border-image: url(:/bg.png);\n"
"    border-radius:20px;\n"
"    color: white;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0.909, y1:0.864, x2:0.926, y2:0, stop:0.448864 #186cdc, stop:1 white);\n"
"}")
        self.cameraButton.setObjectName("cameraButton")
        self.cameraLabel = QtWidgets.QLabel(self.backGroundFrame)
        self.cameraLabel.setGeometry(QtCore.QRect(50, 0, 1031, 621))
        self.cameraLabel.setText("")
        self.cameraLabel.setObjectName("cameraLabel")
        self.returnButton = QtWidgets.QPushButton(FACELOOK)
        self.returnButton.setGeometry(QtCore.QRect(500, 630, 141, 41))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(15)
        self.returnButton.setFont(font)
        self.returnButton.setStyleSheet("QPushButton{\n"
"    border-image: url(:/bg.png);\n"
"    border-radius:20px;\n"
"    color: white;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0.909, y1:0.864, x2:0.926, y2:0, stop:0.448864 #186cdc, stop:1 white);\n"
"}")
        self.returnButton.setObjectName("returnButton")
        self.explainButton = QtWidgets.QPushButton(FACELOOK)
        self.explainButton.setGeometry(QtCore.QRect(800, 630, 141, 41))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(15)
        self.explainButton.setFont(font)
        self.explainButton.setStyleSheet("QPushButton{\n"
"    border-image: url(:/bg.png);\n"
"    border-radius:20px;\n"
"    color: white;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0.909, y1:0.864, x2:0.926, y2:0, stop:0.448864 #186cdc, stop:1 white);\n"
"}")
        self.explainButton.setObjectName("explainButton")

        self.retranslateUi(FACELOOK)
        QtCore.QMetaObject.connectSlotsByName(FACELOOK)

    def retranslateUi(self, FACELOOK):
        _translate = QtCore.QCoreApplication.translate
        FACELOOK.setWindowTitle(_translate("FACELOOK", "Form"))
        self.cameraButton.setText(_translate("FACELOOK", "开始识别"))
        self.returnButton.setText(_translate("FACELOOK", "退出"))
        self.explainButton.setText(_translate("FACELOOK", "解释结果"))
import bg_rc
