# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'emotion2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FACELOOK(object):
    def setupUi(self, FACELOOK):
        FACELOOK.setObjectName("FACELOOK")
        FACELOOK.resize(1149, 710)
        self.backGroundFrame = QtWidgets.QFrame(FACELOOK)
        self.backGroundFrame.setGeometry(QtCore.QRect(0, 0, 1151, 711))
        self.backGroundFrame.setStyleSheet("#backGroundFrame{border-image: url(:/0.png)}")
        self.backGroundFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.backGroundFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.backGroundFrame.setObjectName("backGroundFrame")
        self.cameraButton = QtWidgets.QPushButton(self.backGroundFrame)
        self.cameraButton.setGeometry(QtCore.QRect(600, 630, 141, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.cameraButton.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(15)
        self.cameraButton.setFont(font)
        self.cameraButton.setStyleSheet("QPushButton{\n"
"    border-image: url(:/bg.png);\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:0.909, y1:0.864, x2:0.926, y2:0, stop:0.448864 rgba(255, 239, 88, 250), stop:1 rgba(255, 255, 255, 255));\n"
"    \n"
"}\n"
"")
        self.cameraButton.setObjectName("cameraButton")
        self.returnButton = QtWidgets.QPushButton(self.backGroundFrame)
        self.returnButton.setGeometry(QtCore.QRect(780, 630, 141, 41))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(15)
        self.returnButton.setFont(font)
        self.returnButton.setStyleSheet("QPushButton{\n"
"    border-radius:10px;\n"
"border-image: url(:/bg.png);\n"
"\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:0.909, y1:0.864, x2:0.926, y2:0, stop:0.448864 rgba(255, 239, 88, 250), stop:1 rgba(255, 255, 255, 255));\n"
"    \n"
"}\n"
"")
        self.returnButton.setObjectName("returnButton")
        self.explainButton = QtWidgets.QPushButton(self.backGroundFrame)
        self.explainButton.setGeometry(QtCore.QRect(960, 630, 131, 41))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(15)
        self.explainButton.setFont(font)
        self.explainButton.setStyleSheet("QPushButton{\n"
"    border-radius:10px;\n"
"border-image: url(:/bg.png);\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:0.909, y1:0.864, x2:0.926, y2:0, stop:0.448864 rgba(255, 239, 88, 250), stop:1 rgba(255, 255, 255, 255));\n"
"    \n"
"}\n"
"")
        self.explainButton.setObjectName("explainButton")
        self.cameraLabel = QtWidgets.QLabel(self.backGroundFrame)
        self.cameraLabel.setGeometry(QtCore.QRect(50, 90, 1031, 471))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.cameraLabel.setFont(font)
        self.cameraLabel.setText("")
        self.cameraLabel.setObjectName("cameraLabel")

        self.retranslateUi(FACELOOK)
        QtCore.QMetaObject.connectSlotsByName(FACELOOK)

    def retranslateUi(self, FACELOOK):
        _translate = QtCore.QCoreApplication.translate
        FACELOOK.setWindowTitle(_translate("FACELOOK", "FACELOOK"))
        self.cameraButton.setText(_translate("FACELOOK", "打开摄像头"))
        self.returnButton.setText(_translate("FACELOOK", "退出"))
        self.explainButton.setText(_translate("FACELOOK", "解释结果"))
import bg_rc
